export const fileTypes = [
  {
    fileType: "pdf",
    label: "PDF",
    icon: "ri-file-pdf-2-line",
    colour: "text-red-400",
    hoverBackground: "hover:bg-red-500",
    shadowClass: "shadow-red-400",
    accept: ".pdf",
  },
  {
    fileTypes: "images",
    label: "Images",
    icon: "ri-file-image-line",
    colour: "text-blue-400",
    hoverBackground: "hover:bg-blue-500",
    shadowClass: "shadow-blue-400",
    accept: "image/*",
  },
  {
    fileTypes: "video",
    label: "Video",
    icon: "ri-file-video-line",
    colour: "text-emerald-400",
    hoverBackground: "hover:bg-emerald-700",
    shadowClass: "shadow-emerald-400",
    accept: "video/*",
  },
  {
    fileTypes: "audio",
    label: "Audio",
    icon: "ri-file-music-line",
    colour: "text-amber-400",
    hoverBackground: "hover:bg-amber-500",
    shadowClass: "shadow-amber-400",
    accept: "audio/*",
  },
  {
    fileTypes: "other",
    label: "Other",
    icon: "ri-file-add-line",
    colour: "text-gray-400",
    hoverBackground: "hover:bg-gray-500",
    shadowClass: "shadow-gray-400",
    accept: "*/*",
  },
];
